services:
  postgres:
    image: postgres:15
    container_name: conecta-social-db
    environment:
      POSTGRES_DB: conecta_social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - conecta-network

  app:
    build: .
    container_name: conecta-social-api
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: conecta_social
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: 89a0fb0fca4e6d6ef5e0c57ea291ac4c7c92929b3ee1e086cf37b7ad66b2c0a1
    depends_on:
      - postgres
    networks:
      - conecta-network

volumes:
  postgres_data:

networks:
  conecta-network:
    driver: bridge
